"""High-level reusable VFX framework namespace."""

from .api import vfx
from .anchors import catalog_anchors, resolve_anchor
from .archetypes import catalog_archetypes, resolve_archetype
from .afflict import (
    AfflictionId,
    AfflictionIdLike,
    AfflictionSpec,
    AfflictionTickSpec,
    CustomAfflictionId,
    afflict,
    custom_affliction_id,
)
from .clips import catalog_clips, resolve_clip
from .compiler import compile_archetype, compile_timeline, compile_vfx
from .modifiers import catalog_modifiers, resolve_modifier
from .model import (
    AnchorSpec,
    ArchetypeInstance,
    ArchetypeSpec,
    BudgetSpec,
    ClipInstance,
    ClipSpec,
    ModifierInstance,
    ModifierSpec,
    PhaseSpec,
    TimelineSpec,
    VariationSpec,
    VfxAnchorId,
    VfxAnchorLike,
    VfxArchetypeId,
    VfxArchetypeLike,
    VfxBudgetTier,
    VfxBucket,
    VfxClipId,
    VfxClipLike,
    VfxLod,
    VfxModifierId,
    VfxModifierLike,
    VfxPhaseKind,
    VfxReadiness,
)

__all__ = [
    "vfx",
    "compile_vfx",
    "compile_timeline",
    "compile_archetype",
    "catalog_clips",
    "catalog_modifiers",
    "catalog_anchors",
    "catalog_archetypes",
    "resolve_clip",
    "resolve_modifier",
    "resolve_anchor",
    "resolve_archetype",
    "afflict",
    "AfflictionId",
    "CustomAfflictionId",
    "AfflictionIdLike",
    "AfflictionTickSpec",
    "AfflictionSpec",
    "custom_affliction_id",
    "VfxClipId",
    "VfxModifierId",
    "VfxAnchorId",
    "VfxArchetypeId",
    "VfxBucket",
    "VfxLod",
    "VfxBudgetTier",
    "VfxPhaseKind",
    "VfxReadiness",
    "VfxClipLike",
    "VfxModifierLike",
    "VfxAnchorLike",
    "VfxArchetypeLike",
    "ClipInstance",
    "ModifierInstance",
    "PhaseSpec",
    "TimelineSpec",
    "AnchorSpec",
    "VariationSpec",
    "BudgetSpec",
    "ClipSpec",
    "ModifierSpec",
    "ArchetypeSpec",
    "ArchetypeInstance",
]
