"""Generated IDs from EffectsYamlAbilities.java.

Do not edit manually; re-run scripts/extract_effects_ids.py.
"""

ACTION_TYPES = ['absorb', 'add_resistance', 'animate', 'animate_real_time', 'animate_realtime', 'animate_shape', 'any', 'attach', 'burst', 'chain_damage', 'chain_lightning', 'chance', 'clear_reflect', 'clear_resistance', 'damage', 'damage_chain', 'damage_crit', 'damage_dot', 'damage_falloff', 'damage_ground', 'damage_lifesteal', 'damage_over_time', 'damage_percent', 'damage_true', 'damage_typed', 'debug_log', 'each', 'first', 'follow', 'for_each_target', 'ground_damage', 'heal', 'heal_hot', 'heal_over_time', 'heal_percent', 'hostile_default', 'knockback', 'lock_target', 'lock_to_target', 'loop', 'minion_summon', 'minions', 'motion', 'particles_arc', 'particles_bezier', 'particles_box', 'particles_cone', 'particles_cylinder', 'particles_disk', 'particles_helix', 'particles_line', 'particles_mesh', 'particles_physics', 'particles_physics_mesh', 'particles_physics_points', 'particles_physics_polyline', 'particles_point', 'particles_points', 'particles_polygon', 'particles_polyline', 'particles_ring', 'particles_sphere', 'particles_sphere_fill', 'particles_sphere_filled', 'particles_sphere_shell', 'particles_spline', 'potion', 'preset_beam_chargeup', 'preset_gradient_arc', 'preset_gradient_bezier', 'preset_gradient_box', 'preset_gradient_cone', 'preset_gradient_cylinder', 'preset_gradient_disk', 'preset_gradient_helix', 'preset_gradient_line', 'preset_gradient_polygon', 'preset_gradient_ring', 'preset_gradient_sphere_filled', 'preset_gradient_sphere_shell', 'preset_gradient_spline', 'preset_morph_arc', 'preset_morph_box', 'preset_morph_cone', 'preset_morph_cylinder', 'preset_morph_disk', 'preset_morph_helix', 'preset_morph_line', 'preset_morph_polygon', 'preset_morph_ring', 'preset_morph_sphere_filled', 'preset_morph_sphere_shell', 'preset_orbit', 'preset_orbiting_runes', 'preset_shockwave', 'preset_spiral_aura', 'preset_spline_motion', 'preset_swirl', 'projectile', 'pull', 'pulse', 'pve_only', 'pvp_only', 'raycast_hit_entity', 'sequence', 'set_reflect', 'set_resistance', 'shield', 'sound', 'state_machine', 'summon_minion', 'trail']

TARGETER_TYPES = ['box', 'capsule-ray', 'capsule_ray', 'chain', 'cone', 'cylinder', 'difference', 'ground-snap', 'ground-sphere', 'ground_snap', 'ground_sphere', 'intersection', 'line-of-sight', 'line_of_sight', 'look-ray', 'look_ray', 'los', 'nearest', 'nearest-angle', 'nearest-within-angle', 'nearest_angle', 'nearest_within_angle', 'projectile-hit', 'projectile_hit', 'random', 'random-n', 'random_n', 'self', 'sphere', 'union', 'weighted-distance', 'weighted-threat', 'weighted_distance', 'weighted_threat']

CONDITION_TYPES = ['always', 'and', 'biome', 'caster-has-tag', 'caster-lacks-tag', 'caster_has_tag', 'caster_lacks_tag', 'chance', 'has-item', 'has-item-tag', 'has-tag', 'has-target', 'has_item', 'has_item_tag', 'has_tag', 'has_target', 'health-gte', 'health-lte', 'health-pct-gte', 'health-pct-lte', 'health_gte', 'health_lte', 'health_pct_gte', 'health_pct_lte', 'in-party', 'in_party', 'item-match', 'item_match', 'lacks-tag', 'lacks_tag', 'level-gte', 'level-lte', 'level_gte', 'level_lte', 'mana-gte', 'mana-lte', 'mana-pct-gte', 'mana-pct-lte', 'mana_gte', 'mana_lte', 'mana_pct_gte', 'mana_pct_lte', 'not', 'or', 'party-leader', 'party-size-gte', 'party-size-lte', 'party_leader', 'party_size_gte', 'party_size_lte', 'permission', 'region', 'sneaking', 'stat-gte', 'stat-lte', 'stat_gte', 'stat_lte', 'time-between', 'time_between', 'var-equals', 'var-gt', 'var-gte', 'var-lt', 'var-lte', 'var-present', 'var_equals', 'var_gt', 'var_gte', 'var_lt', 'var_lte', 'var_present', 'world', 'xp-gte', 'xp-lte', 'xp_gte', 'xp_lte']

REQUIREMENT_TYPES = ['has_item_tag', 'permission', 'sneaking']

COST_TYPES = ['consume_item', 'consume_main_hand', 'durability', 'durability_main_hand', 'mana', 'resource']
